/**
 * Overmind — Recipe Service
 *
 * Recipes are repeatable, saved build configurations that capture HOW
 * something should be built: tools, rules, steps, iteration config,
 * LLM tier preferences, and cleanup profiles.
 *
 * When a user requests a build, Overmind checks for matching recipes:
 * 1. Exact target_type match
 * 2. Keyword similarity in description
 * 3. Fallback: suggest top 3 recipes
 *
 * Recipes can be created manually, saved from successful builds, or
 * auto-generated by the LLM planning engine.
 */

import { query } from '../database';
import type { TargetType, WorkflowStep } from './types';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface OvRecipe {
  id: string;
  name: string;
  description: string;
  target_type: TargetType;
  tools: string[];
  rule_overrides: Record<string, unknown>;
  steps: RecipeStep[];
  iteration_config: RecipeIterationConfig;
  cleanup_profile: string;
  llm_tiers: Record<string, string>;
  fleet_preference: string;
  skills: string[];
  model: string;
  usage_count: number;
  last_used_at: Date | null;
  created_by: string;
  created_at: Date;
  updated_at: Date;
}

export interface RecipeStep {
  type: string;
  skill_name?: string;
  disclosure_level?: number;
  llm_tier?: string;
  config?: Record<string, unknown>;
}

export interface RecipeIterationConfig {
  min: number;
  max: number;
  passes?: RecipePassConfig[];
  escalation_mode?: 'escalate' | 'force_complete' | 'pause';
}

export interface RecipePassConfig {
  iteration: number;
  type: 'full_build' | 'focused_fixes' | 'resistance_check' | 'deep_remediation';
  disclosure: number;
  tier: string;
}

export interface CreateRecipeInput {
  name: string;
  description?: string;
  target_type: TargetType;
  tools?: string[];
  rule_overrides?: Record<string, unknown>;
  steps?: RecipeStep[];
  iteration_config?: RecipeIterationConfig;
  cleanup_profile?: string;
  llm_tiers?: Record<string, string>;
  fleet_preference?: string;
  skills?: string[];
  model?: string;
  created_by?: string;
}

// ---------------------------------------------------------------------------
// Row mapper
// ---------------------------------------------------------------------------

function rowToRecipe(row: any): OvRecipe {
  return {
    id: row.id,
    name: row.name,
    description: row.description || '',
    target_type: row.target_type,
    tools: Array.isArray(row.tools) ? row.tools : [],
    rule_overrides: row.rule_overrides || {},
    steps: Array.isArray(row.steps) ? row.steps : [],
    iteration_config: row.iteration_config || { min: 2, max: 5 },
    cleanup_profile: row.cleanup_profile || 'normal',
    llm_tiers: row.llm_tiers || {},
    fleet_preference: row.fleet_preference || 'auto',
    skills: Array.isArray(row.skills) ? row.skills : [],
    model: row.model || 'coder',
    usage_count: row.usage_count || 0,
    last_used_at: row.last_used_at || null,
    created_by: row.created_by || 'system',
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}

// ---------------------------------------------------------------------------
// CRUD
// ---------------------------------------------------------------------------

export async function createRecipe(input: CreateRecipeInput): Promise<OvRecipe> {
  const { rows } = await query(
    `INSERT INTO overmind_recipes (name, description, target_type, tools, rule_overrides, steps, iteration_config, cleanup_profile, llm_tiers, fleet_preference, skills, model, created_by)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
     RETURNING *`,
    [
      input.name,
      input.description || '',
      input.target_type,
      JSON.stringify(input.tools || []),
      JSON.stringify(input.rule_overrides || {}),
      JSON.stringify(input.steps || []),
      JSON.stringify(input.iteration_config || { min: 2, max: 5 }),
      input.cleanup_profile || 'normal',
      JSON.stringify(input.llm_tiers || {}),
      input.fleet_preference || 'auto',
      JSON.stringify(input.skills || []),
      input.model || 'coder',
      input.created_by || 'system',
    ]
  );
  return rowToRecipe(rows[0]);
}

export async function getRecipe(id: string): Promise<OvRecipe | null> {
  const { rows } = await query('SELECT * FROM overmind_recipes WHERE id = $1', [id]);
  return rows.length > 0 ? rowToRecipe(rows[0]) : null;
}

export async function listRecipes(targetType?: TargetType): Promise<OvRecipe[]> {
  if (targetType) {
    const { rows } = await query(
      'SELECT * FROM overmind_recipes WHERE target_type = $1 ORDER BY usage_count DESC, updated_at DESC',
      [targetType]
    );
    return rows.map(rowToRecipe);
  }
  const { rows } = await query(
    'SELECT * FROM overmind_recipes ORDER BY usage_count DESC, updated_at DESC'
  );
  return rows.map(rowToRecipe);
}

export async function updateRecipe(
  id: string,
  updates: Partial<CreateRecipeInput>
): Promise<OvRecipe | null> {
  const fields: string[] = [];
  const values: unknown[] = [];
  let idx = 1;

  if (updates.name !== undefined) {
    fields.push(`name = $${idx++}`);
    values.push(updates.name);
  }
  if (updates.description !== undefined) {
    fields.push(`description = $${idx++}`);
    values.push(updates.description);
  }
  if (updates.target_type !== undefined) {
    fields.push(`target_type = $${idx++}`);
    values.push(updates.target_type);
  }
  if (updates.tools !== undefined) {
    fields.push(`tools = $${idx++}`);
    values.push(JSON.stringify(updates.tools));
  }
  if (updates.rule_overrides !== undefined) {
    fields.push(`rule_overrides = $${idx++}`);
    values.push(JSON.stringify(updates.rule_overrides));
  }
  if (updates.steps !== undefined) {
    fields.push(`steps = $${idx++}`);
    values.push(JSON.stringify(updates.steps));
  }
  if (updates.iteration_config !== undefined) {
    fields.push(`iteration_config = $${idx++}`);
    values.push(JSON.stringify(updates.iteration_config));
  }
  if (updates.cleanup_profile !== undefined) {
    fields.push(`cleanup_profile = $${idx++}`);
    values.push(updates.cleanup_profile);
  }
  if (updates.llm_tiers !== undefined) {
    fields.push(`llm_tiers = $${idx++}`);
    values.push(JSON.stringify(updates.llm_tiers));
  }
  if (updates.fleet_preference !== undefined) {
    fields.push(`fleet_preference = $${idx++}`);
    values.push(updates.fleet_preference);
  }
  if (updates.skills !== undefined) {
    fields.push(`skills = $${idx++}`);
    values.push(JSON.stringify(updates.skills));
  }
  if (updates.model !== undefined) {
    fields.push(`model = $${idx++}`);
    values.push(updates.model);
  }

  if (fields.length === 0) return getRecipe(id);

  fields.push(`updated_at = NOW()`);
  values.push(id);

  const { rows } = await query(
    `UPDATE overmind_recipes SET ${fields.join(', ')} WHERE id = $${idx} RETURNING *`,
    values
  );
  return rows.length > 0 ? rowToRecipe(rows[0]) : null;
}

export async function deleteRecipe(id: string): Promise<boolean> {
  const result = await query('DELETE FROM overmind_recipes WHERE id = $1', [id]);
  return (result.rowCount ?? 0) > 0;
}

/**
 * Record usage of a recipe (increments counter and updates last_used_at).
 */
export async function recordRecipeUsage(id: string): Promise<void> {
  await query(
    `UPDATE overmind_recipes SET usage_count = usage_count + 1, last_used_at = NOW(), updated_at = NOW() WHERE id = $1`,
    [id]
  );
}

// ---------------------------------------------------------------------------
// Recipe Matching
// ---------------------------------------------------------------------------

/**
 * Find the best matching recipe for a given target type and description.
 *
 * Matching priority:
 * 1. Exact target_type match, ordered by usage_count (most popular first)
 * 2. Return top N matches for the user to choose from
 *
 * @returns Top matching recipes (up to 3)
 */
export async function findMatchingRecipes(
  targetType: TargetType,
  description?: string,
  limit: number = 3
): Promise<OvRecipe[]> {
  // First: exact target_type matches
  const { rows } = await query(
    `SELECT * FROM overmind_recipes
     WHERE target_type = $1
     ORDER BY usage_count DESC, updated_at DESC
     LIMIT $2`,
    [targetType, limit]
  );

  if (rows.length > 0) {
    return rows.map(rowToRecipe);
  }

  // Fallback: any recipe, sorted by popularity
  const { rows: fallback } = await query(
    `SELECT * FROM overmind_recipes
     ORDER BY usage_count DESC, updated_at DESC
     LIMIT $1`,
    [limit]
  );
  return fallback.map(rowToRecipe);
}

const STOP_WORDS = new Set([
  'the', 'and', 'for', 'with', 'this', 'that', 'from', 'have', 'has',
  'been', 'will', 'can', 'want', 'need', 'like', 'just', 'make', 'get',
  'use', 'some', 'could', 'would', 'should', 'about', 'into', 'also',
  'please', 'help', 'something', 'what', 'how', 'why', 'when', 'where',
]);

/**
 * Match playbooks against a free-text user message.
 * Scores each playbook by keyword overlap with its name, description,
 * target_type, tools, and skills. Returns the best match if the score
 * exceeds a threshold, otherwise null.
 *
 * Also returns the full recipe list so callers can avoid a second query.
 */
export async function matchPlaybookToIntent(
  message: string
): Promise<{ match: OvRecipe | null; allRecipes: OvRecipe[] }> {
  if (!message || message.trim().length < 5) {
    return { match: null, allRecipes: [] };
  }

  const { rows } = await query(
    'SELECT * FROM overmind_recipes ORDER BY usage_count DESC, updated_at DESC'
  );
  const allRecipes = rows.map(rowToRecipe);
  if (allRecipes.length === 0) return { match: null, allRecipes };

  const words = message.toLowerCase().split(/\s+/)
    .filter(w => w.length >= 4 && !STOP_WORDS.has(w));

  if (words.length === 0) return { match: null, allRecipes };

  let bestScore = 0;
  let bestRecipe: OvRecipe | null = null;

  for (const recipe of allRecipes) {
    const haystack = [
      recipe.name,
      recipe.description,
      recipe.target_type.replace(/_/g, ' '),
      ...recipe.tools,
      ...recipe.skills,
    ]
      .join(' ')
      .toLowerCase();

    let score = 0;
    for (const word of words) {
      if (haystack.includes(word)) score++;
    }

    if (score > bestScore) {
      bestScore = score;
      bestRecipe = recipe;
    }
  }

  return { match: bestScore >= 3 ? bestRecipe : null, allRecipes };
}

/**
 * Convert a recipe into the JobConfig format used by createJob().
 * This bridges the recipe system with the existing job creation pipeline.
 */
export function recipeToJobConfig(recipe: OvRecipe): {
  min_iterations: number;
  max_iterations: number;
  cleanup_thresholds: {
    max_low: number;
    max_medium: number;
    max_high: number;
    fail_on_critical: boolean;
  };
  workflow: WorkflowStep[];
  recipe_id: string;
  recipe_name: string;
  tools: string[];
  llm_tiers: Record<string, string>;
  iteration_passes: RecipePassConfig[];
} {
  const overrides = recipe.rule_overrides as Record<string, any>;

  return {
    min_iterations: recipe.iteration_config.min,
    max_iterations: recipe.iteration_config.max,
    cleanup_thresholds: {
      max_low: overrides?.thresholds?.max_low ?? 10,
      max_medium: overrides?.thresholds?.max_medium ?? 3,
      max_high: overrides?.thresholds?.max_high ?? 0,
      fail_on_critical: overrides?.thresholds?.fail_on_critical ?? true,
    },
    workflow: recipe.steps.map(s => ({
      type: s.type as any,
      skill_name: s.skill_name,
      config: s.config,
    })),
    recipe_id: recipe.id,
    recipe_name: recipe.name,
    tools: recipe.tools,
    llm_tiers: recipe.llm_tiers,
    iteration_passes: recipe.iteration_config.passes || [],
  };
}

// ---------------------------------------------------------------------------
// Built-in Recipe Templates
// ---------------------------------------------------------------------------

/** Default recipes that can be seeded on first run. */
export const BUILT_IN_RECIPES: CreateRecipeInput[] = [
  {
    name: 'Next.js Production App',
    description: 'Full production web application with TypeScript, Tailwind, auth, and deployment',
    target_type: 'web_app',
    tools: ['typescript', 'tailwind', 'supabase', 'vercel-deploy'],
    steps: [
      { type: 'spec', skill_name: 'spec-writer', disclosure_level: 2 },
      { type: 'implementation', skill_name: 'focused-builder', disclosure_level: 2 },
      { type: 'cleanup', skill_name: 'iterate', disclosure_level: 3 },
      { type: 'test', skill_name: 'preflight-app', disclosure_level: 2 },
      { type: 'deploy', skill_name: 'vercel-deploy', disclosure_level: 1 },
    ],
    iteration_config: {
      min: 2,
      max: 5,
      passes: [
        { iteration: 1, type: 'full_build', disclosure: 2, tier: 'coder' },
        { iteration: 2, type: 'focused_fixes', disclosure: 1, tier: 'light' },
        { iteration: 3, type: 'resistance_check', disclosure: 3, tier: 'coder' },
        { iteration: 4, type: 'deep_remediation', disclosure: 3, tier: 'heavy' },
      ],
      escalation_mode: 'escalate',
    },
    cleanup_profile: 'strict',
    llm_tiers: { plan: 'heavy', build: 'coder', cleanup: 'light', review: 'medium' },
    fleet_preference: 'auto',
    skills: ['spec-writer', 'focused-builder', 'iterate', 'preflight-app'],
    model: 'coder',
  },
  {
    name: 'Landing Page',
    description: 'Quick marketing landing page with responsive design',
    target_type: 'website',
    tools: ['typescript', 'tailwind', 'vercel-deploy'],
    steps: [
      { type: 'spec', disclosure_level: 1 },
      { type: 'implementation', skill_name: 'focused-builder', disclosure_level: 2 },
      { type: 'cleanup', skill_name: 'iterate', disclosure_level: 2 },
      { type: 'deploy', disclosure_level: 1 },
    ],
    iteration_config: {
      min: 1,
      max: 3,
      passes: [
        { iteration: 1, type: 'full_build', disclosure: 2, tier: 'coder' },
        { iteration: 2, type: 'focused_fixes', disclosure: 1, tier: 'light' },
      ],
      escalation_mode: 'force_complete',
    },
    cleanup_profile: 'normal',
    llm_tiers: { plan: 'medium', build: 'coder', cleanup: 'light' },
    fleet_preference: 'auto',
    skills: ['focused-builder', 'iterate'],
    model: 'coder',
  },
  {
    name: 'API Backend',
    description: 'Node.js/Express API with database, auth, and Docker deployment',
    target_type: 'web_app',
    tools: ['typescript', 'express', 'postgresql', 'docker'],
    steps: [
      { type: 'spec', disclosure_level: 2 },
      { type: 'implementation', skill_name: 'focused-builder', disclosure_level: 2 },
      { type: 'cleanup', skill_name: 'iterate', disclosure_level: 3 },
      { type: 'test', disclosure_level: 2 },
    ],
    iteration_config: {
      min: 2,
      max: 5,
      passes: [
        { iteration: 1, type: 'full_build', disclosure: 2, tier: 'coder' },
        { iteration: 2, type: 'focused_fixes', disclosure: 1, tier: 'coder' },
        { iteration: 3, type: 'resistance_check', disclosure: 3, tier: 'heavy' },
      ],
      escalation_mode: 'escalate',
    },
    cleanup_profile: 'strict',
    llm_tiers: { plan: 'heavy', build: 'coder', cleanup: 'coder', review: 'heavy' },
    fleet_preference: 'auto',
    skills: ['focused-builder', 'iterate'],
    model: 'coder',
  },
];
